name: Helm Actions
run-name: Helm Actions
on: [push]

jobs:
  Helm-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm and Tree
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update --yes
          sudo apt-get install helm --yes
          sudo apt-get install tree --yes

      - name: Disable SSL verify (Temporary Fix)
        run: git config --global http.sslVerify false

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Tree
        run: tree

      - name: Add helm-common repo
        run: helm repo add --username ynnckvdv --password ${{ secrets.PASSWORD }} helm-common https://gitea.swell.casa:3000/api/packages/ynnckvdv/helm --insecure-skip-tls-verify

      - name: Helm Repo Update
        run: helm repo update

      - name: Helm Dependency Update
        run: helm dependency update --insecure-skip-tls-verify

      - name: Helm Dependency Build
        run: helm dependency build . --insecure-skip-tls-verify

      - name: Helm Package to create .tgz file
        run: helm package .
        
      - name: Push Helm Chart to packages
        run: curl --insecure --user ynnckvdv:${{ secrets.ACTION_TOKEN }} -X POST --upload-file *.tgz https://gitea.swell.casa:3000/api/packages/ynnckvdv/helm/api/charts -v
